version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: ozmap_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: